config/routes.rb
Rails.application.routes.draw do

  root to: "frontend#index"
  get 'book/:id', to: "frontend#book", as: "frontend_book"
  get 'admin', to: "users#index"
  resources :users, path: "admin/users"
  resources :books, path: "admin/books"

  namespace :api do
    get 'v1/index'
    get 'v1/book/:id', to: "v1#book", as: "v1_book"
  end


  devise_for :users, :skip => [:registrations]
    as :user do
      get 'user/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # if item is filed
  def self.filed(_filed = false)
    where(deleted: _filed)
  end
  # if is active
  def self.published
    where(status: true, deleted: false)
  end
end

app/models/book.rb
class Book < ApplicationRecord
  # Reference a user
  belongs_to :user, optional: true

  #validations name, description, :image, author
  validates :name, :description, :image, :author, presence: true
  validates :name,:author,length: {in: 3..50}
  validates :description, length: {in: 10..300}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #validation name
  validates_presence_of :name
  validates :name, length: {in: 3..50}
end

app/controllers/api/v1_controller.rb
module Api
  class V1Controller < ActionController::API
    # Return all items and links
    def index
      page_number = params[:page].try(:[], :number)
      #per_page = params[:page].try(:[], :size)
      @books = Book.published.order(name: :asc).page(page_number).per(8)
      render json: @books
    end
    # Find book by id
    def book
      @book = Book.published.find(params[:id])
      render json: @book
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.filed(false).order(:id).page(params[:page]).per(10)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.deleted = true
    @book.save
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.filed(false).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :description, :image, :author, :status)
    end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  skip_before_action :authenticate_user!

  # Render index page and show 12 books
  def index
  end
  # Render book
  def book

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.filed(false).order(:id).page(params[:page]).per(10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.deleted = true
    @user.save
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.filed(false).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.


    def password_blank?
      params[:user][:password].blank? &&
          params[:user][:password_confirmation].blank?
    end

    def user_params
      if password_blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :status)
    end
end

app/helpers/api/v1_helper.rb
module Api::V1Helper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :author %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book, class: "btn btn-info" %> |
<%= link_to 'Back', books_path, class: "btn btn-success" %>

app/views/books/index.html.erb
<% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
<% end %>

<div class="row">
  <div class="col-md-8">
    <h1>Books</h1>
  </div>
  <div class="col-md-4 text-right">
    <%= link_to 'New Book', new_book_path, class: "btn btn-success" %>
  </div>
</div>
<table class="table table-striped table-responsive">
  <thead class="thead-inverse">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.description %></td>
        <td><img src="<%= book.image %>" alt="<%= book.name %>" style="max-width: 100px"></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center row">
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong style="display:block">Image:</strong>
  <img src='<%= @book.image %>'>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<%= link_to 'Edit', edit_book_path(@book), class: "btn btn-info" %> |
<%= link_to 'Back', books_path, class: "btn btn-success" %>

app/views/frontend/book.html.erb
<div class="book">
  <div class="container">
    <div id="app">
      <h1>{{item.name}}</h1>
      <article>
        <div class="row d-flex justify-content-center">
          <div class="col-md-4">
            <img v-bind:src="item.image" class="img">
            <p>
              {{item.description}}
            </p>
            <small>
              <b>Author:</b> {{item.author}}
            </small>
          </div>
        </div>
      </article>
      <div class="row d-flex justify-content-center buttons">
        <a href="/" class="btn btn-xs btn-info">back</a>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag('book') %>

app/views/frontend/index.html.erb
<div class="index">
  <div class="container">
    <h1>Books</h1>
    <div id="app">
      <div class="row">
        <div class="search">
          <input type="text" v-model="search" placeholder="Search title.."/>
        </div>
      </div>
      <div class="row">
        <div class="selection">
          <select v-model="sort" class="custom-select">
            <option value="">Sort by</option>
            <option v-for="item in options" v-bind:value="item">
              {{item}}
            </option>
          </select>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6 col-md-3 d-flex flex-nowrap" v-for="item in filteredList ">
          <div class="card">
            <img class="card-img-top" v-bind:src="item.attributes.image" alt="Card image cap">
            <div class="card-body">
              <h4 class="card-title">{{item.attributes.name}}</h4>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <p>
                <small><b>Author:</b> {{item.attributes.author}}</small>
              </p>
              <a v-bind:href="item.attributes.url" class="btn btn-primary">more</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row d-flex justify-content-center buttons">
        <button class="btn btn-info btn-sm" v-show="links.prev" @click="changePage(links.prev)">prev</button>
        <button class="btn btn-info btn-sm" v-show="links.next" @click="changePage(links.next)">next</button>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag('main') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sumone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= "justify-content-center" if devise_controller? %>">
    <%= render partial: "layouts/shared/header" if user_signed_in? %>
    <% if devise_controller? %>
    <div class="d-flex justify-content-center align-items-center d-flex flex-nowrap">
      <div class="col-md-4 align-self-center">
        <%= yield %>
      </div>
    </div>
    <%
    else
      concat content_tag('div', yield, class: "container page")
    end
    %>
  </body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sumone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'frontend', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'frontend' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= "active" if controller_name == "users" %>">
          <%= link_to "users", users_path, class: "nav-link"  %>
        </li>
        <li class="nav-item <%= "active" if controller_name == "books" %>">
          <%= link_to "books", books_path, class: "nav-link"  %>
        </li>
      </ul>

      <div class="col-md-2 d-flex justify-content-md-end justify-content-sm-start">
        <div class="row">
          <%= link_to("logout", destroy_user_session_path, class: "btn btn-outline-warning btn-sm", method: "delete", data: { confirm: 'Are you sure you want to quit?' }) %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.input :admin %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class: "btn btn-info" %> |
<%= link_to 'Back', users_path, class: "btn btn-success" %>

app/views/users/index.html.erb
<% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
<% end %>

<div class="row">
  <div class="col-md-8">
    <h1>Users</h1>
  </div>
  <div class="col-md-4 text-right">
    <%= link_to 'New User', new_user_path, class: "btn btn-success" %>
  </div>
</div>
<table class="table table-striped table-responsive">
  <thead class="thead-inverse">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Admin</th>
    <th>Status</th>
    <th colspan="3">
      Actions
    </th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.status %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: "btn btn-success" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>



<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-info" %> |
<%= link_to 'Back', users_path, class: "btn btn-success" %>